### ISSUE TITLE
v1.2.0 design sprint

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#112]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to track the work being done on the current design sprint for the v1.1.0 release.

## 🎨 Design Changes

- [x] The Scribe app icon and key being given a more modern style (closes #24)
- [x] The logo for Scribe being reworked to give the app a distinct style (closes issues in [Organization](https://github.com/scribe-org/Organization))
- [x] The app screen being completely redone to be more appealing (closes #28)
- [x] Vertical spacing being added between the keys to make them easier to press
- [x] The keyboard buttons being made slightly wider and smaller to reflect the system keyboard
- [x] The keyboard command view being revamped to create an appealing new interface
- [x] The keys being shaded to resemble the system keyboard more (closes #32)
- [x] Keyboard colors in light and dark mode being updated to match system keyboards
- [x] The keyboard always switching to an English input when translating to make the functionality more clear
- [x] The app texts and keys being made less opaque to make them easier on the eyes
- [x] The colors of the Scribe key icon being changed to match that of the other keys
- [x] Key corners being made less rounded to give them a blockier look
- [x] The Scribe command interface now being sized relative to the keyboard (closes #29)
- [x] Scribe command buttons being shaded to make them more apparent on the keyboard
- [x] Keyboard layouts being changed to reflect dynamic sizing of the command interface and be more similar to system keyboards
- [x] The shift conjugation state buttons being restyled to be more apparent
- [x] Translation prompts being changed to just be two digit abbreviations of source and target language
- [x] Colors for noun annotation being updated to improve readability (closes #31)
- [x] Noun annotation with a square symbol to represent the gender
- [x] Preposition annotation with a rectangular symbol to represent the case
- [x] Preposition case abbreviations being changed to match the language of they keyboard
  - The above two close #92 
- [x] Key characters and command prompts being made slightly smaller for iPads in landscape mode
- [x] Users being able to get to the settings by clicking the directions in the app screen (closes #27)
- [x] All App Store media being redone to reflect these changes (closes #114)

### Contribution

Designs courtesy of Spencer Arney

**Comment by andrewtavis** [comment]
### Current progress

<div align="left">
  <img src="https://user-images.githubusercontent.com/24387426/150890520-399715d7-3071-4404-9085-9554cb646e53.png" width=300>
</div>

**Comment by andrewtavis** [comment]
#32 is closed, but the new keys still need their tap areas increased to cover the screen. This will be done using the methods in [this SO question](https://stackoverflow.com/questions/31056703/how-can-i-increase-the-tap-area-for-uibutton).

**Comment by andrewtavis** [comment]
With 1fa2bd3 done the last thing that's needed is the App Store videos :)

**Comment by andrewtavis** [comment]
Final tests will happen tomorrow before sending v1.2.0 in for review.
